Repository sunflower-cmd/GraduationThesis_CarServices, pull requests merged in 2023-05, with the labels that each got.

#8 Temporary complete Garage, Product, Review basic functions
  Controllers/GarageController.cs
  Models/DTO/Product/CreateProductDto.cs
  Models/DTO/Product/DeleteProductDto.cs
  Models/DTO/Product/ProductDto.cs
  Models/DTO/Product/UpdateProductDto.cs
  Models/DTO/Review/CreateReviewDto.cs
  Models/DTO/Review/ReviewDto.cs
  Repositories/Repository/ProductRepository.cs
  Repositories/Repository/ReviewRepository.cs
  Services/Service/ProductService.cs
  Services/Service/ReviewService.cs
Labels: bug, invalid, wontfix

#13 Able to merge.
  Controllers/BookingController.cs
  Enum/BookingStatus.cs
  Enum/LotStatus.cs
  Mapping/AutoMapperConfiguration.cs
  Models/DTO/Booking/BookingCheckRequestDto.cs
  Models/DTO/Booking/BookingCreateRequestDto.cs
  Models/DTO/Booking/BookingDetailResponseDto.cs
  Models/DTO/Booking/BookingPerHour.cs
  Models/DTO/Garage/GarageDetailResponseDto.cs
  Models/DTO/Garage/ServiceGarageGarageDto.cs
  Models/DataContext.cs
  Models/Entity/Booking.cs
  Models/Entity/Garage.cs
  Models/Entity/Lot.cs
  Models/Entity/Service.cs
  Repositories/IRepository/IBookingRepository.cs
  Repositories/IRepository/ICarRepository.cs
  Repositories/IRepository/ILotRepository.cs
  Repositories/IRepository/IServiceRepository.cs
  Repositories/Repository/BookingRepository.cs
  Repositories/Repository/CarRepository.cs
  Repositories/Repository/GarageRepository.cs
  Repositories/Repository/LotRepository.cs
  Repositories/Repository/ServiceRepository.cs
  Services/IService/IBookingService.cs
  Services/Service/BookingService.cs
  Services/Service/GarageService.cs
Labels: bug, documentation, enhancement, good first issue, wontfix

#14 Quyền
  Controllers/ProductController.cs
  Controllers/ReviewController.cs
  Controllers/ServiceController.cs
  Mapping/AutoMapperConfiguration.cs
  Models/DTO/Product/ProductCreateRequestDto.cs
  Models/DTO/Product/ProductDetailResponseDto.cs
  Models/DTO/Product/ProductListResponseDto.cs
  Models/DTO/Product/ProductMediaFileDto.cs
  Models/DTO/Product/ProductMediaFileProductDto.cs
  Models/DTO/Product/ProductQuantityRequestDto.cs
  Models/DTO/Product/ProductStatusRequestDto.cs
  Models/DTO/Product/ProductUpdateRequestDto.cs
  Models/DTO/Product/ServiceProductDto.cs
  Models/DTO/Product/SubcategoryProductDto.cs
  Models/DTO/Review/CustomerReviewDto.cs
  Models/DTO/Review/DeleteReviewDto.cs
  Models/DTO/Review/GarageReviewDto.cs
  Models/DTO/Review/ReviewCreateRequestDto.cs
  Models/DTO/Review/ReviewDetailResponseDto.cs
  Models/DTO/Review/ReviewListResponseDto.cs
  Models/DTO/Review/ReviewStatusRequestDto.cs
  Models/DTO/Review/ReviewUpdateRequestDto.cs
  Models/DTO/Review/UserReviewDto.cs
  Models/DTO/Service/GarageServiceDto.cs
  Models/DTO/Service/ProductServiceDto.cs
  Models/DTO/Service/ServiceCreateRequestDto.cs
  Models/DTO/Service/ServiceDetailResponseDto.cs
  Models/DTO/Service/ServiceGarageServiceDto.cs
  Models/DTO/Service/ServiceListResponseDto.cs
  Models/DTO/Service/ServiceStatusRequestDto.cs
  Models/DTO/Service/ServiceUpdateRequestDto.cs
  Repositories/IRepository/IProductRepository.cs
  Repositories/IRepository/IReviewRepository.cs
  Repositories/IRepository/IServiceRepository.cs
  Repositories/Repository/ProductRepository.cs
  Repositories/Repository/ReviewRepository.cs
  Repositories/Repository/ServiceRepository.cs
  Services/IService/IProductService.cs
  Services/IService/IReviewService.cs
  Services/IService/IServiceService.cs
  Services/Service/ProductService.cs
  Services/Service/ReviewService.cs
  Services/Service/ServiceService.cs
Labels: bug, invalid
